### ISSUE TITLE
[Feature Request] Ansible Galaxy publish

### ISSUE THREAD

**Issue by 3deep5me** [h3po/ansible-role-proxmox_cloudimage#3]
Hello @h3po,

i really like you work it saves me a lot of time. Did you ever thought about to publish this as a role on ansible galaxy? Then it would be easier for me to add the role/playbook to my "global" playbook. 

Thank you for sharing this!

**Comment by h3po** [comment]
Hi, nice to hear it's useful for someone. I haven't considered spending the time to polish this for galaxy, imho it would require a pretty extensive test suite. You can still just install the role via ansible-galaxy by specifying the git url as described here: https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-a-specific-version-of-a-role

**Comment by 3deep5me** [comment]
Thanks!
Didn't knew this - just a part-time ansible guy.  
This should work for me!
